'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("mock2Launcher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _131() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("131", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _131_UPDATE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("131_UPDATE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _131Updated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_131Updated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _132() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_132", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _132EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("132EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _134() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_134", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _134EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_134EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _135() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_135", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _135EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_135EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _136() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_136", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _136EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_136EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _137() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_137", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _137EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_137EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _138() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_138", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _138EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_138EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _139() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_139", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _139EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("139EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _139EN1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("139EN1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _140() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_140", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _140EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_140EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _141() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_141", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _141EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_141EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _142() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_142", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _142EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("142EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _143() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_143", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _143EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_143EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _144() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_144", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _144EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_144EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _145() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_145", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _145EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_145EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _146() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_146", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _146EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_146EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _147() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_147", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _147EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_147EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _148() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_148", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _148EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_148EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _149() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_149", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _149EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_149EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _150() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_150", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _150EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_150EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _151() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_151", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _151EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_151EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _152() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_152", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _152EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_152EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _153() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_153", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _153EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_153EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _154() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_154", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _154EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_154EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _155() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_155", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _155EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_155EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _156() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_156", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _156EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_156EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _157() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_157", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _157EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_157EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _158() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_158", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _158EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_158EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _159() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_159", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _159EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_159EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _160EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_160EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _161EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_161EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _162() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_162", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _162EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_162EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _163() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_163", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _163EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_163EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _164() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_164", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _164EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_164EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _165() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_165", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _165EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_165EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _166() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_166", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _166EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("166EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _167() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_167", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _167EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_167EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _168() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_168", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _168EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_168EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _169() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_169", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _169EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("169EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _170() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_170", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _170ENPLAY1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_170ENPLAY1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _170JPPLAY1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_170JPPLAY1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _171() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_171", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _171ENPLAY1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_171ENPLAY1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _171JPPLAY1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_171JPPLAY1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _172() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_172", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _172EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("172EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _172JPPLAY2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("172JPPLAY2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _172JPPLAY3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("172JPPLAY3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _172JPPLAY4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("172JPPLAY4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _172JPPLAY5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("172JPPLAY5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _173() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_173", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _173EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_173EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _174() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_174", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _174EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_174EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _175() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_175", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _175EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("175EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _176() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_176", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _176EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_176EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _177() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_177", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _177EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_177EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _178() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_178", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _178EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_178EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _179() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_179", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _179EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_179EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _180() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_180", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _180EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_180EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _181() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_181", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _181EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_181EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _182() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_182", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _182EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_182EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _183() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_183", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _183EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_183EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _184() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_184", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _184EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_184EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _185() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_185", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _185EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_185EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _186() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_186", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _186EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_186EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _187() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_187", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _187EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_187EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _188() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_188", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _188EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_188EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _189() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_189", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _189EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_189EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _190() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_190", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _190EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_190EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _191() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_191", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _191EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_191EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _192() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_192", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _192EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_192EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _193() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_193", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _193EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_193EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _194() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_194", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _194EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_194EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _195() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_195", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _195EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_195EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _196() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_196", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _196EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_196EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _197__Japanese__Japan__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_197__Japanese__Japan__", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _198__Japanese__Japan__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_198__Japanese__Japan__", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _206() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_206", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _207__Japanese__Japan__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_207__Japanese__Japan__", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _208__Japanese__Japan__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_208__Japanese__Japan__", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _209__Japanese__Japan__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_209__Japanese__Japan__", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _215() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_215", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _219() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_219", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _219EN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_219EN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _290__Japanese__Japan__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_290__Japanese__Japan__", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _30994__Japanese__Japan__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_30994__Japanese__Japan__", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _30996__Japanese__Japan__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_30996__Japanese__Japan__", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property blankBTN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blankBTN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property blankCBTN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blankCBTN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property blankHBTN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blankHBTN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property cur30977() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("cur30977", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property ddraw() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ddraw", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DownloadTemplate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DownloadTemplate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not locate &quot;pso2.exe&quot;.  Please check your root path has the following bin folder.  &quot;pso2_bin&quot; and &quot;pso2.exe&quot; located within it..
        '''</summary>
        Public ReadOnly Property noPSO2Found() As String
            Get
                Return ResourceManager.GetString("noPSO2Found", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to backup your files before applying the patch? This will erase all previous Pre-EN patch backups..
        '''</summary>
        Public ReadOnly Property strBackupEN() As String
            Get
                Return ResourceManager.GetString("strBackupEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR.
        '''</summary>
        Public ReadOnly Property strERROR() As String
            Get
                Return ResourceManager.GetString("strERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to backup your files before applying the patch? This will erase all previous Pre-Large Files patch backups..
        '''</summary>
        Public ReadOnly Property strWouldYouLikeToBackupLargeFiles() As String
            Get
                Return ResourceManager.GetString("strWouldYouLikeToBackupLargeFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to use a pre-downloaded RAR file containing the patch instead of downloading it now?.
        '''</summary>
        Public ReadOnly Property strWouldYouLikeToUse() As String
            Get
                Return ResourceManager.GetString("strWouldYouLikeToUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public ReadOnly Property user() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("user", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
